### ISSUE TITLE
How can we get the crowdhuman_hybrid_branch.pth?

### ISSUE THREAD

**Issue by wi11Iam5-mpu** [HDETR/H-TransTrack#1]
Thanks for your excellent work! I noticed the  option '--resume' in r50_hybrid_branch_lambda0.5_group5_t1000_dp0_lft_transtrack_for_val.sh using a pretrained model, cally ' crowdhuman_hybrid_branch.pth'. But, I cannot find it in this repo. So, may I get this model?

**Comment by PkuRainBow** [comment]
@HaojunYuPKU Please help to address the issue.

**Comment by HaojunYu1998** [comment]
Thanks for your interest. I will release the checkpoint ASAP.
